apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-token
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: cloudflare-token
  data:
    - secretKey: token
      remoteRef:
        key: k8s/cert-manager
        property: cloudflare_token
