name: openbao

services:
  openbao:
    container_name: openbao
    image: openbao/openbao:2.7.0@sha256:71156a1c6623a5fa3f5e61b0c6a8ead0faf0df29a778339188443551995d1315
    command: ["server", "-config=/openbao/config/openbao.hcl"]
    restart: unless-stopped
    environment:
      BAO_API_ADDR: https://openbao.home.${DOMAIN}
    volumes:
      - ./openbao.hcl:/openbao/config/openbao.hcl:ro
      - /srv/openbao:/openbao/data
    networks:
      - backend

networks:
  backend:
    name: backend
    external: true
