- name: Restart smbd
  ansible.builtin.systemd_service:
    name: smbd
    state: restarted

- name: Restart nfs-server
  ansible.builtin.systemd_service:
    name: nfs-server
    state: restarted

- name: Reload exports
  ansible.builtin.command: exportfs -ra
  changed_when: true

- name: Restart smartd
  ansible.builtin.systemd_service:
    name: smartmontools
    state: restarted
