proxmox_host_files: "{{ playbook_dir }}/../proxmox"
proxmox_host_deadman_minutes: 5

proxmox_host_acme_account: default
proxmox_host_acme_email: "{{ homelab_config.acme_email }}"
proxmox_host_acme_directory: https://acme-v02.api.letsencrypt.org/directory

proxmox_host_tofu_user: tofu@pve
proxmox_host_tofu_role: TofuProvisioner
proxmox_host_tofu_privs:
  - Datastore.AllocateSpace
  - Datastore.AllocateTemplate
  - Datastore.Audit
  - SDN.Use
  - Sys.Audit
  - Sys.Modify
  - VM.Allocate
  - VM.Audit
  - VM.Backup
  - VM.Clone
  - VM.Config.CDROM
  - VM.Config.CPU
  - VM.Config.Cloudinit
  - VM.Config.Disk
  - VM.Config.HWType
  - VM.Config.Memory
  - VM.Config.Network
  - VM.Config.Options
  - VM.GuestAgent.Audit
  - VM.PowerMgmt

proxmox_host_tofu_backup_role: TofuBackupStorage
proxmox_host_tofu_backup_path: /storage/local
proxmox_host_tofu_backup_privs:
  - Datastore.Allocate
  - Datastore.AllocateSpace
  - Datastore.AllocateTemplate
  - Datastore.Audit
