apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nas
  resources:
    requests:
      storage: 500Gi
