apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
  namespace: immich
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18-standard-trixie
  managed:
    roles:
      - name: app
        ensure: present
        login: true
        passwordSecret:
          name: immich-database-credentials
      - name: power_tools
        ensure: present
        login: true
        inRoles:
          - pg_read_all_data
        connectionLimit: 10
        passwordSecret:
          name: immich-power-tools-database
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 1Gi
  storage:
    storageClass: longhorn
    size: 5Gi
  postgresql:
    shared_preload_libraries:
      - vchord.so
    extensions:
      - name: vchord
        image:
          reference: ghcr.io/tensorchord/vchord-scratch:pg18-v1.1.1
        dynamic_library_path:
          - /usr/lib/postgresql/18/lib
        extension_control_path:
          - /usr/share/postgresql/18/
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich-database
  namespace: immich
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  name: app
  owner: app
  cluster:
    name: immich-database
  extensions:
    - name: vector
      ensure: present
    - name: vchord
      ensure: present
    - name: earthdistance
      ensure: present
    - name: cube
      ensure: present
