apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: intel-device-plugins
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/intel/intel-device-plugins-for-kubernetes
  ref:
    tag: v0.37.1
  ignore: |
    /*
    !/deployments/gpu_plugin/
