all:
  children:
    proxmox:
      hosts:
        pve:
          ansible_host: "{{ lookup('ansible.builtin.env', 'PROXMOX_HOST') }}"
          ansible_user: root
    openbao:
      hosts:
        openbao:
          ansible_host: "{{ lookup('ansible.builtin.env', 'PROXMOX_HOST') }}"
          ansible_user: root
          ansible_connection: community.proxmox.proxmox_pct_remote
          proxmox_vmid: 130
    garage:
      hosts:
        garage:
          ansible_host: "{{ lookup('ansible.builtin.env', 'PROXMOX_HOST') }}"
          ansible_user: root
          ansible_connection: community.proxmox.proxmox_pct_remote
          proxmox_vmid: 140
    services:
      hosts:
        services:
          ansible_host: 192.168.1.30
          ansible_user: debian
          ansible_ssh_common_args: >-
            -o ProxyJump=root@{{ lookup('ansible.builtin.env', 'PROXMOX_HOST') }}
            -o StrictHostKeyChecking=accept-new
