name: manifests

on:
  workflow_dispatch:

permissions: {}

jobs:
  flux-schema:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: fluxcd/flux-schema/actions/setup@fac00ee3cb2fb0bd904c77e9e7727e98ba8a3c05 # v0.15.0
        with:
          version: v0.15.0
      - run: >-
          flux-schema validate gitops
          --schema-location default
          --schema-location ecosystem
          --envsubst-file .github/flux-schema.env
          --envsubst-strict
