name: renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"

permissions: {}

concurrency:
  group: renovate

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: renovatebot/github-action@230ce922b08968d0a4f6f70f295601daff09ef1d # v46.3.7
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          renovate-version: 44.135.0
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_ONBOARDING: "false"
          RENOVATE_REQUIRE_CONFIG: required
          RENOVATE_GIT_AUTHOR: "jotavare <38820667+jotavare@users.noreply.github.com>"
          LOG_LEVEL: info
